- name: Add proxy
  blockinfile:
    path: /etc/environment
    block: |
      HTTP_PROXY={{ proxy }}
      HTTPS_PROXY={{ proxy }}
      http_proxy={{ proxy }}
      https_proxy={{ proxy }}
      no_proxy=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au

- name: Update apt
  apt:
    upgrade: yes
    update_cache: yes
  
- name: install dependencies
  apt:
    name: ['apt-transport-https', 'build-essential', 'ca-certificates', 'curl', 'git', 'python3-dev', 'python3-pip', 'python3-setuptools', 'software-properties-common', 'unzip', 'vim']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Update pip
  pip:
    name: ['pip']
    state: latest

- name: add ~/.vimrc
  template:
    src: "vimrc.j2"
    dest: "/home/{{ ansible_user }}/.vimrc"