- name: Create instances
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ item.flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ item.security_groups }}'
    network: '{{ instance_network }}'
    # volumes: "{{ item.volume_ids }}"
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: os_instance
  loop: '{{ instances }}'

- name: Set ip address to fact
  set_fact:
    ip_addresses: "{{ ip_addresses|default([]) + [ {'name': item.openstack.name, 'ip': item.openstack.public_v4} ] }}"
  when: item.openstack is defined
  loop: '{{ os_instance.results }}'

- debug:
    var: ip_addresses

- name: Create inventory file on disk
  copy:
    content: "[{{ host_groups }}]\n"
    dest: '{{ host_file }}'

- name: Add ip addresses to inventory file
  lineinfile:
    line: "{{ item.ip }}\n"
    dest: '{{ host_file }}'
  loop: '{{ ip_addresses }}'
