- name: create couchdb directory
  file:
    path: '{{ db_dir }}'
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: configure compose
  tags: couchdb
  template:
    src: docker-compose.yaml.j2
    dest: "{{ db_dir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"


- name: run docker compose
  tags: couchdb
  docker_compose:
    project_src: "{{ db_dir }}"
    pull: yes
    state: present
    remove_orphans: yes
    recreate: always