#   CouchDB
couchdb_version: 2.3.0
couchdb_config_path: /home/ubuntu/couchdb/etc
couchdb_share: 4
couchdb_replica: 3
cluster_cookie: 'hello'
cluster_communication_port_min: 9100
cluster_communication_port_max: 9102


#   Docker
enable_docker_remote_control: true