- name: Create directory
  file:
    path: '/etc/systemd/system/docker.service.d'
    recurse: yes
    state: directory

- name: change docker proxy | step 2
  blockinfile:
    path: /etc/systemd/system/docker.service.d/http-proxy.conf
    create: yes
    block: |
        [Service]
        Environment="HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/"
        Environment="HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/"
        Environment="http_proxy=http://wwwproxy.unimelb.edu.au:8000/"
        Environment="https_proxy=http://wwwproxy.unimelb.edu.au:8000/"
        Environment="no_proxy=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"
  

- name: change docker proxy | step 3
  command: '{{ item }}'
  with_items:
    - systemctl daemon-reload
    - systemctl restart docker
