- name: copy configure file
  template:
    src: "{{ ansible_nodename }}.yaml.j2"
    dest: "{{ working_dir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: unzip SA2
  unarchive:
    src: '{{ working_dir }}/aurin/SA2.json.zip'
    dest: '{{ working_dir }}/aurin/'
    remote_src: yes

- name: run docker compose
  docker_compose:
    project_src: "{{ working_dir }}"
    build: yes
    # state: absent
    remove_orphans: yes
    remove_volumes: yes
    recreate: always
