FROM python:3.7-slim

WORKDIR /workspace
COPY requirement.txt ./
RUN pip install --no-cache-dir -r requirement.txt \
    && pip install --no-cache-dir shapely ujson

STOPSIGNAL SIGINT

ENTRYPOINT [ "python", "-u" ]
CMD "add_sa.py"