FROM python:3.7-alpine

WORKDIR /workspace
ADD . /workspace
COPY config/cronjobs /etc/crontabs/root

RUN apk add --update --no-cache --virtual .build-deps \
    g++ gcc libxslt-dev && \
    pip install --no-cache-dir -r stream_requirement.txt && \
    apk del .build-deps

CMD ["crond", "-f", "-d", "8"]