- name: build Docker image
  docker_image:
    name: python
    build:
      path: '{{ working_dir }}/harvester'
      pull: yes
    source: build
    force_source: yes
    tag: "90024"

- name: start container
  docker_container:
    name: timeline
    image: python:90024
    log_driver: json-file
    log_options:
      max-size: 10m
    # state: stopped
    # restart: yes
    command: api_dig.py
    volumes:
      - '{{ working_dir }}/harvester:/workspace'